%% File with constnt settings for CCLM calibration suite
%
%% directories:
%  -- simdir
%  -- obsdir
%%  calibration time period
%  --nmonths
%  --nyear
%  --nyearstart
%  --nyearend
%% Parameters, simulations and domains
%  --nparam
%  --nsim
%  --expid
%  --paramn
%  --paramnt
%  --regnames
%  --default param
%  --range of param
%% Independent simulations
%  --nind
%  --valdata


simdir='/hymet/ssilje/CALIBRATION_CA_emmanuele/data/long_calibration/';
obsdir='/hymet/ssilje/CALIBRATION_CA_emmanuele/data/bellprat_obs/';


nyear=5;
nmonths=nyear*12;
% For the internal variability stddata_2000-2009.mat
nyearstart=1;
nyearend=5;
nparam=9; %number of parameters
nsim=2*nparam*nparam; %number of simulations
% expid={'rl','v','tk','u','ra','f','l','tu'};
% % Define Parameters
% paramn={'rlam_heat','v0snow','tkhmin','uc1','radfac','roodtp','l_g','tur_len'}; % No TEX interpreter
%paramnt={'rlam\_heat','v0snow','tkhmin','uc1','radfac','roodtp','l\_g','tur\_len'}; % No TEX interpreter
%expid={'rl','v','tk','u','ra','d','s','e', 'q'};
expid={'d', 'rl' , 'tk', 'v','ra' , 's', 'u', 'q' , 'e' };


% Define Parameters
paramn={'d_mom','rlam_heat', 'tkhmin', 'v0snow',  'radfac' , 'soilh' ,'uc1', 'qi0' , 'e_surf'}; % No TEX interpreter
paramnt={'d\_mom','rlam\_heat', 'tkhmin', 'v0snow', 'radfac', 'soilh' , 'uc1', 'qi0' , 'e\_surf'}; % No TEX interpreter


regnames={'clu1','clu2','clu3','clu4','clu5','clu6','clu7','clu8', 'clu9', 'clu10', 'clu11'};


%%% To reduce the chances of typing in wrong numbers, copy in from
%%% INPUT_ORG in the input folder.

rlam_heat=1.0;
v0snow=25;
tkhmin=0.4;
uc1=0.8;
radfac=0.5;
d_mom=16.6;
soilh=1.62;
e_surf=1;
qi0=0;
%% logarithmic variables: rlam_heat; e_surf;  soilhyd

% Default parameters
default={[d_mom log(rlam_heat) tkhmin v0snow radfac log(soilh) uc1 qi0 log(e_surf)]};


%%% To reduce the chances of typing in wrong numbers, copy in the line from
%%% the script generate_input.m here:

rlam_heatn=0.1;
rlam_heatx=10;
v0snown=10;
v0snowx=15;
tkhminn=0;
tkhminx=2;
uc1n=0.2;
uc1x=1.6;
radfacn=0.3;
radfacx=0.9;
d_momn=12;
d_momx=15;
soilhn=0.1;
soilhx=10;
e_surfn=0.1;
e_surfx=10;
qi0n=0.00001;
qi0x=0.0001;

%% logarithmic variables: rlam_heat; e_surf; soilhyd
% Parameter ranges (min,max)
range={[d_momn d_momx];
    [log(rlam_heatn) log(rlam_heatx)];
    [tkhminn tkhminx];
    [v0snown v0snowx];
    [radfacn radfacx];
    [log(soilhn) log(soilhx)];
    [uc1n uc1x];
    [qi0x qi0n];
    [log(e_surfn) log(e_surfx)];};






nind=3; % number of independent simulations
%%% Matrix for 1 independent simulations
% The independent runs can be generated by this function:
%[xexp]=create_validation_experiments(parameters,lhacc)

%valdata  %now setting it to default
%valdata=[d_mom log(rlam_heat) tkhmin v0snow radfac log(soilh) uc1 qi0  log(e_surf)];
valdata=[3.2188 log(4.2212) 1.6346 13.7661 0.4749 log(0.3169) 1.2902 0.0000 log(3.0281); % IND1
    13.9604 log(2.3665) 1.7370 10.4912 0.3222 log(2.5761) 1.3508 0.0000 log(0.5657); %IND2
   12.5804 log(0.5954) 0.1231 14.9506 0.8710 log(0.2903) 0.8493 0.0001 log(6.6516)]; %IND3



